common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('pybo/', views.index),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
]

pybo/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('common/', include('common.urls')),
]

common/models.py
from django.db import models

# Create your models here.

pybo/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label='Email')

    class Meta:
        model = User
        fields = ('username', 'email')

pybo/forms.py
from django import forms
from pybo.models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class':'form-control'}),
        #     'content': forms.Textarea(attrs={'class':'form-control', 'rows':10})
        # }
        labels = {
            'subject': 'Title',
            'content': 'Content',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': 'Reply',
        }

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm
# Create your views here.

def signup(request):
    """
    Create ID
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form':form})

pybo/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.http import HttpResponse
from .models import Question
from django.utils import timezone
from .forms import QuestionForm, AnswerForm
from django.core.paginator import Paginator

def index(request):
    """
    print pybo list
    """
    page = request.GET.get('page', '1')
    question_list = Question.objects.order_by('-create_date')
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question_list':page_obj}
    return render(request, 'pybo/question_list.html', context)
    # return HttpResponse("Hi, Welcome to pybo")

def detail(request, question_id):
    """
    print pybo list
    """
    question = get_object_or_404(Question, pk=question_id)
    # question = Question.objects.get(id=question_id)
    context = {'question':question}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
    register pybo reply
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:index', question_id=question_id)
    else:
        form = AnswerForm()

    context = {'question':question, 'form':form}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def question_create(request):
    """
    register pybo question
    """
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()

    context = {'form':form}
    return render(request, 'pybo/question_form.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        <!-- pybo CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <title> Hello, pybo welcome to test Version! </title>
    </head>
    <body>
        <!-- Start Content -->
        <!-- Navigation Bar -->
        {% include "navbar.html" %}
        <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
            <a class="navbar-brand" href="{% url 'pybo:index' %}"> Pybo </a>
            <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item ">
                        <a class="nav-link" href="#"> Login </a>
                    </li>
                </ul>
            </div>
        </nav> -->
        {% block content %}
        {% endblock %}
        <!-- jQuery JS -->
        <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
        <!-- Bootstrap JS -->
        <script src="{% static 'bootstrap.min.js' %}"></script>
        <!-- End Content -->
    </body>
</html>

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4> Login </h4>
        </div>
        <div class="col-8 text-right">
            <span>
                Or <a href="{% url 'common:signup' %}"> Create ID </a>
            </span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <!-- URL to move after sign in -->
        <input type="hidden" name="next" value="{{ next }}">
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username"> User ID </label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>    
        <div class="form-group">
            <label for="password"> Password </label>
            <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary"> Login </button>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4> Create ID </h4>
        </div>
        <div class="col-8 text-right">
            <span> Or <a href="{% url 'common:login' %}"> Sign in </a></span>
        </div>
    </div>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username"> Username </label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1"> Password </label>
            <input type="password" class="form-control" name="password1" id="password1" value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2"> Confirm Password </label>
            <input type="password" class="form-control" name="password2" id="password2" value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email"> Email </label>
            <input type="text" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary"> Create </button>
    </form>
</div>
{% endblock %}

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %} <!-- Field Error -->
            <div class="alert alert-danger">
                    <strong> {{ field.label }} </strong>
                    {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %} <!-- Non-Field Error -->
        <div class="alert alert-danger">
            <strong> {{ error }} </strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}"> Pybo </a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">
                    {{ user.username }} (Logout)
                </a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}"> Login </a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2"> {{ question.subject}} </h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;"> {{ question.content}} </div>
        </div>
        <div class="d-flex justify-content-end">
            <div class="badge badge-light p-2"> {{question.create_date}} </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py2"> Count of Reply are {{ question.answer_set.count }} </h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;"> {{ answer.content }} </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2"> {{ answer.create_date }} </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if forms.errors %}
        <div class="alert alert-danger" role="alert">
            {% for fields in form %}
                {% if fields.errors %}
                <strong> {{ field.label }} </strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea name="content" id="content" \
            {% if not user.is_authenticated %} disabled {% endif %} \
             class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="Register Reply" class="btn btn-primary">
    </form>
</div>
{% endblock %}


<!-- {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <h2 class="border-bottom py-2"> {{ question.subject}} </h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;"> {{ question.content}} </div>
        </div>
        <div class="d-flex justify-content-end">
            <div class="badge badge-light p-2"> {{question.create_date}} </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py2"> Count of Reply are {{ question.answer_set.count }} </h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;"> {{ answer.content }} </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2"> {{ answer.create_date }} </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="Register Reply" class="btn btn-primary">
    </form>
</div> -->

<!-- <h1>
    {{ question.subject }}
</h1>

<div>
    {{ question.content}}
</div>

<h5>
    Count of Reply are {{ question.answer_set.count }}
</h5>

<div>
    <ul>
        {% for answer in question.answer_set.all %}
        <li>
            {{ answer.content }}
        </li>
        {% endfor %}
    </ul>
</div>

<form action="{% url 'pybo:answer_create' question.id %}" method="post">
    {% csrf_token %}
    <textarea name="content" id="content" rows="15"></textarea>
    <input type="submit" value="Regist Reply">
</form> -->

templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2"> Register Question </h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- Start Error -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong> {{ field.label }} </strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- End Error -->
        <div class="form-group">
            <label for="subject"> Title </label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content"> Content </label>
            <textarea class="form-control" name="content" id="content" rows="10">
                {{ form.content.value|default_if_none:''}}
            </textarea>
        </div>
        <!-- {{ form.as_p }} -->
        <button type="submit" class="btn btn-primary"> Save </button>
    </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th> Number </th>
                <th> Title </th>
                <th> Posting Time </th>
            </tr>
        </thead>
        <tbody>
            {% if question_list %}
            {% for question in question_list %}
            <tr>
                <!-- <td> {{ forloop.counter }} </td> -->
                <td>
                    {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
                </td>
                <td>
                    <a href="{% url 'pybo:detail' question.id %}">
                        {{ question.subject }}
                    </a>
                    {% if question.answer_set.count > 0 %}
                    <span class="text-danger small ml-2">
                        {{ question.answer_set.count }}
                    </span>
                    {% endif %}
                </td>
                <td> {{ question.create_date }} </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3"> No Questions </td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <!-- Start to Page -->
    <ul class="pagination justify-content-center">
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}"> Previous </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"> Previous </a>
        </li>
        {% endif %}
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item activate" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}"> {{ page_number }} </a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}"> {{ page_number }} </a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.nexzt_page_number }}"> Next </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"> Next </a>
        </li>
        {% endif %}
    </ul>
    <!-- End to Page -->
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary"> Register Question </a>
</div>
{% endblock %}

<!-- {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th> Number </th>
                <th> Title </th>
                <th> Posting Time </th>
            </tr>
        </thead>
        <tbody>
            {% if question_list %}
            {% for question in question_list %}
            <tr>
                <td> {{ forloop.counter }} </td>
                <td>
                    <a href="{% url 'pybo:detail' question.id %}">
                        {{ question.subject }}
                    </a>
                </td>
                <td> {{ question.create_date}} </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3"> No Questions </td>
            </tr>
            {% endif %}
        </tbody>
    </table>
</div> -->

<!-- {% if question_list %}
    <ul>
        {% for question in question_list %}
            <li>
                <a href="/pybo/{{ question.id }}/">
                <a href="{% url 'pybo:detail' question.id %}">
                    {{ question.subject }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>
        No Questions
    </p>
{% endif %} -->